<?php

namespace AppBundle\Repository;

//use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function findProductsWithPriceGreaterThan($minPrice)
	{
		$qb = $this->createQueryBuilder('p');
		$qb
			->where('p.price > :price')
			->orderBy('p.price', 'ASC');

		$query = $qb->getQuery();
		/*$query = $this->getEntityManager()->createQuery(
			'SELECT p
			FROM AppBundle:Product p
			WHERE p.price > :price'
		);*/

		$query->setParameter('price', $minPrice);
		return $query->getResult();
	}
}
