AppBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            unique: true
        price:
            type: decimal
            precision: '5'
            scale: '2'
        description:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
